In [31]:
import dgl
import torch 
import numpy as np
from dgl.utils import expand_as_pair
import mxnet as mx

In [51]:
u = [0,0,2]
v = [1,2,3]
g = dgl.graph((u,v))
g = dgl.to_bidirected(g)

In [52]:
g.ndata['feat'] = torch.ones(g.num_nodes(),3)

In [53]:
print(g.out_degrees())

tensor([2, 1, 2, 1])


In [54]:
feat_src, feat_dst = expand_as_pair(g.ndata['feat'] , g)

In [55]:
print(feat_src)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [56]:
degs = g.out_degrees()
norm = degs
shp = norm.shape + (1,) * (feat_src.ndim - 1)
print(degs)
norm = norm.reshape(shp)
print(shp)
feat_src = feat_src * norm
print(norm)
print(feat_src)

tensor([2, 1, 2, 1])
torch.Size([4, 1])
tensor([[2],
        [1],
        [2],
        [1]])
tensor([[2., 2., 2.],
        [1., 1., 1.],
        [2., 2., 2.],
        [1., 1., 1.]])
